name: mrx_chansa
description: "A new Flutter project."
publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.31.1
  firebase_auth: ^4.19.6
  firebase_ui_auth: ^1.14.0
  google_sign_in: ^6.2.1
  firebase_ui_oauth_google: ^1.3.2
  provider: ^6.1.2
  cloud_firestore: ^4.17.4
  lottie: ^3.1.2
  share: ^2.0.4
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
