// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX6T4Li1W2sRY0Mn9KTzbpLLnZE_g525E',
    appId: '1:891348732908:web:f2ce9b9e6e645df9a44ec9',
    messagingSenderId: '891348732908',
    projectId: 'flutterfire-ui-codelab-c93c4',
    authDomain: 'flutterfire-ui-codelab-c93c4.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-c93c4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSJHjJFdwqibjCSmAxfV8YY3v471Q8kUg',
    appId: '1:891348732908:android:939e2177511135b2a44ec9',
    messagingSenderId: '891348732908',
    projectId: 'flutterfire-ui-codelab-c93c4',
    storageBucket: 'flutterfire-ui-codelab-c93c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzhF3vN98HeLY7esUXV4u3tNLKrz7O3TQ',
    appId: '1:891348732908:ios:1cf05f853813bf89a44ec9',
    messagingSenderId: '891348732908',
    projectId: 'flutterfire-ui-codelab-c93c4',
    storageBucket: 'flutterfire-ui-codelab-c93c4.appspot.com',
    iosClientId: '891348732908-8sfljl58idnujcspp3tuf34pq5ohc6ig.apps.googleusercontent.com',
    iosBundleId: 'com.example.mrxChansa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzhF3vN98HeLY7esUXV4u3tNLKrz7O3TQ',
    appId: '1:891348732908:ios:1cf05f853813bf89a44ec9',
    messagingSenderId: '891348732908',
    projectId: 'flutterfire-ui-codelab-c93c4',
    storageBucket: 'flutterfire-ui-codelab-c93c4.appspot.com',
    iosClientId: '891348732908-8sfljl58idnujcspp3tuf34pq5ohc6ig.apps.googleusercontent.com',
    iosBundleId: 'com.example.mrxChansa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX6T4Li1W2sRY0Mn9KTzbpLLnZE_g525E',
    appId: '1:891348732908:web:3a9437e7714bc956a44ec9',
    messagingSenderId: '891348732908',
    projectId: 'flutterfire-ui-codelab-c93c4',
    authDomain: 'flutterfire-ui-codelab-c93c4.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-c93c4.appspot.com',
  );
}
